package com.projectmodule.common.identity;

import java.security.SecureRandom;
import java.time.Instant;
import java.util.UUID;

/**
 * Generates time-ordered UUID version 7 identifiers (RFC 9562).
 *
 * <p>Identifiers are generated by the application rather than the database so that an
 * aggregate holds a valid identity from the moment it is constructed, before it is persisted.
 *
 * <p>Version 7 is used instead of the random version 4 because the leading 48 bits are a
 * millisecond timestamp. Sequentially generated keys append to the right-hand edge of a
 * B-tree index instead of scattering across it, which keeps insert performance and index
 * locality predictable as tables grow.
 */
public final class UuidV7 {

    private static final SecureRandom RANDOM = new SecureRandom();

    private static final long VERSION_7 = 0x7L << 12;
    private static final long VARIANT_RFC_4122 = 0x8000000000000000L;
    private static final long TIMESTAMP_MASK = 0xFFFFFFFFFFFFL;
    private static final long VARIANT_CLEAR_MASK = 0x3FFFFFFFFFFFFFFFL;

    private UuidV7() {
    }

    /** Generates an identifier stamped with the current time. */
    public static UUID generate() {
        return generate(Instant.now());
    }

    /**
     * Generates an identifier stamped with the supplied instant.
     *
     * <p>Package-private overload so ordering behaviour can be tested deterministically.
     */
    static UUID generate(Instant instant) {
        long timestamp = instant.toEpochMilli();

        // 48 bits timestamp | 4 bits version | 12 bits random
        long mostSignificantBits = (timestamp & TIMESTAMP_MASK) << 16
                | VERSION_7
                | RANDOM.nextInt(0x1000);

        // 2 bits variant | 62 bits random
        long leastSignificantBits = (RANDOM.nextLong() & VARIANT_CLEAR_MASK) | VARIANT_RFC_4122;

        return new UUID(mostSignificantBits, leastSignificantBits);
    }

    /** Extracts the embedded millisecond timestamp from a version 7 identifier. */
    public static long timestampOf(UUID uuid) {
        if (uuid.version() != 7) {
            throw new IllegalArgumentException("not a version 7 UUID: " + uuid);
        }
        return uuid.getMostSignificantBits() >>> 16;
    }
}
